ARCH:
  LR: 0.1
  ENTROPY_REGULARIZATION: True
  ENTROPY_REGULARIZATION_WEIGHT: 10.
  ENTROPY_PERIOD: (0.0, 0.0)
  L1_REGULARIZATION: False
  L1_REGULARIZATION_WEIGHT: 5.
  L1_PERIOD: (0.0, 0.0)
  HARD_ARCH_TRAINING: False
  HARD_WEIGHT_TRAINING: True
  HARD_EVAL: True
  SEARCHSPACE: GeneralizedMTLNAS
MODEL:
  BACKBONE: VGG16_13_Stage
  INIT: (1.0, 0.0)
  NET1_CLASSES: 40
  NET2_CLASSES: 3
TRAIN:
  EVAL_CKPT: True
  LOG_INTERVAL: 500
  LR: 0.001
  SAVE_INTERVAL: 5000
  WEIGHT_1: Seg
  WEIGHT_2: Normal